name: Publish to PyPI and TestPyPI

on:
  workflow_run:
    workflows: ["Python package"]
    types: [completed]
    branches:
      - develop
      - master
      - main
  pull_request:
    branches:
      - master
      - main
    types: [opened, synchronize]
  push:
    branches:
      - develop  # Publish to TestPyPI on develop push
    tags:
      - 'v*'  # Publish to PyPI on version tags
  release:
    types: [published]  # Trigger when a release is published via GitHub UI
  workflow_dispatch:
    inputs:
      publish_to_testpypi:
        description: 'Publish to TestPyPI'
        required: false
        default: true
        type: boolean
      publish_to_pypi:
        description: 'Publish to PyPI (only works on tags)'
        required: false
        default: false
        type: boolean

permissions:
  contents: read

jobs:
  # Run tests for PRs and develop pushes
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || (github.event_name == 'push' && github.ref == 'refs/heads/develop')
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install poetry
      run: pipx install poetry
    
    - name: Install dependencies
      run: poetry install --no-interaction
    
    - name: Run tests
      run: poetry run pytest tests/ -v
    
  build:
    name: Build Distribution Packages
    runs-on: ubuntu-latest
    needs: [test]
    if: |
      always() && 
      (needs.test.result == 'success' || needs.test.result == 'skipped') &&
      (github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success')

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Needed for git-based versioning

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install poetry
      run: pipx install poetry

    - name: Set version for TestPyPI
      if: (github.event_name == 'pull_request' || (github.event_name == 'push' && github.ref == 'refs/heads/develop')) && !startsWith(github.ref, 'refs/tags/')
      run: |
        # Get current version from pyproject.toml (specifically from [tool.poetry] section)
        CURRENT_VERSION=$(grep '^version = ' pyproject.toml | head -1 | cut -d'"' -f2)

        # Create appropriate dev version
        if [[ "${{ github.event_name }}" == "pull_request" ]]; then
          # For PRs, embed PR number at the end of timestamp
          # Format: 0.1.0.dev202507182301220060 (last 4 digits are zero-padded PR number)
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          PR_NUM=$(printf "%04d" ${{ github.event.pull_request.number }})
          DEV_VERSION="${CURRENT_VERSION}.dev${TIMESTAMP}${PR_NUM}"
        else
          # For develop branch pushes
          DEV_VERSION="${CURRENT_VERSION}.dev$(date +%Y%m%d%H%M%S)"
        fi

        echo "Setting version to $DEV_VERSION for TestPyPI"
        # Update version in pyproject.toml
        sed -i.bak "s/^version = \".*\"/version = \"$DEV_VERSION\"/" pyproject.toml
        rm pyproject.toml.bak

    - name: Build package
      run: poetry build

    - name: Check build artifacts
      run: |
        ls -la dist/
        # Verify wheel and sdist were created
        test -f dist/*.whl
        test -f dist/*.tar.gz

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: python-package-distributions
        path: dist/

  publish-to-testpypi:
    name: Publish to TestPyPI
    needs: build
    runs-on: ubuntu-latest
    # Publish to TestPyPI on:
    # - Pull requests to master/main branch
    # - Push to develop branch
    # - Successful workflow_run from develop branch
    # - Manual workflow dispatch with publish_to_testpypi=true
    if: |
      (github.event_name == 'pull_request' && (github.base_ref == 'master' || github.base_ref == 'main')) ||
      (github.event_name == 'push' && github.ref == 'refs/heads/develop') ||
      (github.event_name == 'workflow_run' && github.event.workflow_run.head_branch == 'develop' && github.event.workflow_run.conclusion == 'success') ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.publish_to_testpypi == 'true')

    environment:
      name: testpypi
      url: https://test.pypi.org/p/powerloom-eigenda

    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/

    - name: List distribution files
      run: ls -la dist/

    - name: Publish to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
        skip-existing: true  # Skip if version already exists
        verbose: true
        attestations: false  # Disable attestations to avoid Rekor server issues

  publish-to-pypi:
    name: Publish to PyPI
    needs: build
    runs-on: ubuntu-latest
    # Only publish to PyPI on version tags or release events
    if: |
      startsWith(github.ref, 'refs/tags/v') ||
      (github.event_name == 'release' && github.event.action == 'published') ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.publish_to_pypi == 'true' && startsWith(github.ref, 'refs/tags/'))

    environment:
      name: pypi
      url: https://pypi.org/p/powerloom-eigenda

    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/

    - name: List distribution files
      run: ls -la dist/

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        verbose: true
        # No skip-existing for production PyPI - we want it to fail if version exists
